# Generated by Django 4.2 on 2024-10-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='submitter',
            new_name='owner',
        ),
    ]
